version: '3'
services:
  app:
    build: docker/node
    ports:
      - 8080:8080
    volumes:
      - ./:/src/
    working_dir: /src/
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true